# fly.toml app configuration file generated for discord-chat-bot-with-memory on 2026-05-08T17:34:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-chat-bot-with-memory'
primary_region = 'sin'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = '8080'
  BOT_PREFIX = '!'
  TYPHOON_BASE_URL = 'https://api.opentyphoon.ai/v1'
  TYPHOON_MODEL = 'typhoon-v2.5-30b-a3b-instruct'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
